apiVersion: helm.hops.ops.com.ai/v1alpha1
kind: OpenTelemetryOperator
metadata:
  name: opentelemetry-operator
  namespace: example-env
spec:
  clusterName: example-cluster
  labels:
    team: platform
  namespace: opentelemetry-operator
  values:
    manager:
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 64Mi
